name: run regression test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        run: sudo apt-get -y install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config libipc-run-perl
      - name: Get PostgreSQL Sources
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
      - name: Configure PostgreSQL
        run: ./configure --enable-cassert --enable-debug --enable-tap-tests
      - name: Build PostgreSQL
        run: make -j4
# TODO: cache the build output
# XXX: Should we change the job here?
      - name: Get pg_count_roles Sources
        uses: actions/checkout@v4
        with:
          path: contrib/pg_count_roles
      - name: Build pg_count_roles
        run: |
          cd contrib/pg_count_roles
          make -j4
      - name: Test pg_count_roles
        run: |
          cd contrib/pg_count_roles
          make check
